### ISSUE TITLE
Error happens when trying to update to EEO 1.0.4

### ISSUE THREAD

**Issue by minisauruslepro** [capasha/EEOEditor#1]
![image](https://user-images.githubusercontent.com/39227035/124916622-dc706380-dfc0-11eb-81b9-031326528729.png)

Also when I download EEO 1.0.4 I am actually downloading 1.0.3 for some reason.

**Comment by capasha** [comment]
I know that people use this tool for EEO. But I'm coding on another project right now and don't have time or want to care about this tool anymore.

**Comment by capasha** [comment]
Fixed in 1.0.5 and update tool 1.0.4
