### ISSUE TITLE
EEOditor having issues to load a large filled map

### ISSUE THREAD

**Issue by minisauruslepro** [capasha/EEOEditor#2]
I can´t open a map that has a lot of content, (38kb)

It freezes EEOditor forever.

Updated the EEO file here in case of needed:
https://www.mediafire.com/file/v4sokkla62ov2ea/Wip_battle_system_2_-_grimoire_-_PWk577hQwWckI.eelvl/file

**Comment by capasha** [comment]
EEOditor doesn't support big worlds. Because at the moment EEOditor use 1 image where you draw images on. And if this image get too big. It will crash, because GDI doesn't support big images.

**Comment by atillabyte** [comment]
This is fixed by #3

**Comment by capasha** [comment]
Fixed in 1.0.5
